import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const plugin = {
    name: 'visual_reporter',
    version: '1.0.0',
    description: 'Generates visual reports (PDF, Charts) to prove work done.',

    tools: [
        {
            name: 'generate_pdf_report',
            description: 'Generates a professional PDF report with title, formatted content, and metadata. Useful for summarizing research or long analyses.',
            parameters: {
                type: 'object',
                properties: {
                    title: { type: 'string', description: 'The main title of the report' },
                    content: { type: 'string', description: 'The body text. Supports newlines (\\n).' },
                    filename: { type: 'string', description: 'Filename without extension (e.g. research_report)' },
                    sections: {
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                heading: { type: 'string' },
                                text: { type: 'string' }
                            }
                        },
                        description: 'Optional: Structured sections for better formatting'
                    }
                },
                required: ['title', 'content', 'filename']
            }
        }
    ],

    /**
     * Executes the requested tool (Standard Loader Signature)
     */
    async execute(args: any, context: any, toolName: any) {
        const { transport, chatId } = context || {};

        if (!transport || !chatId) {
            return { success: false, message: 'CONTEXT_ERROR: Missing required context.' };
        }

        if (toolName === 'generate_pdf_report') {
            return await this.generatePdfReport(args, transport, chatId);
        }
        return { success: false, message: `Unknown tool: ${toolName}` };
    },

    /**
     * Generates a PDF and sends it
     */
    async generatePdfReport({ title, content, filename, sections }: any, transport: any, chatId: any) {
        try {
            const safeFilename = (filename || 'report').replace(/[^a-z0-9]/gi, '_').toLowerCase();
            const tempDir = path.join(__dirname, '..', '..', 'temp');
            if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });

            const filePath = path.join(tempDir, `${safeFilename}_${Date.now()}.pdf`);

            // Document creation
            const doc = new PDFDocument({ margin: 50 });
            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Header
            doc.fontSize(20).text(title, { align: 'center', underline: true });
            doc.moveDown();
            doc.fontSize(10).text(`Generated by Erina (WhatsApp Bot) - ${new Date().toLocaleString()}`, { align: 'right', italic: true });
            doc.moveDown(2);

            // Main Content
            doc.fontSize(12).text(content, {
                align: 'justify',
                paragraphGap: 5
            });

            // Optional Sections
            if (sections && Array.isArray(sections)) {
                doc.moveDown();
                for (const section of sections) {
                    if (section.heading) {
                        doc.moveDown();
                        doc.fontSize(14).text(section.heading, { bold: true });
                        doc.moveDown(0.5);
                    }
                    if (section.text) {
                        doc.fontSize(12).text(section.text, { align: 'justify', paragraphGap: 5 });
                    }
                }
            }

            // Footer
            doc.fontSize(8).text('HiveMind V3 Architecture - Antigravity Agent', 50, doc.page.height - 50, {
                align: 'center',
                color: 'grey'
            });

            doc.end();

            // Wait for stream to finish
            await new Promise((resolve: any) => stream.on('finish', resolve));

            // Send the document
            await transport.sendFile(chatId, filePath, `${title}.pdf`, `📄 Here is the requested report: *${title}*`);

            // Cleanup (Optional: keep for debug or delete?)
            // For now we keep, a cron job (tempCleanup) will handle it

            return {
                success: true,
                message: `PDF generated and sent: ${filePath}`,
                file_path: filePath
            };

        } catch (error: any) {
            console.error('[VisualReporter] PDF generation error:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }
};

export default plugin;
