export interface Message {
    id: string;
    sender: 'user' | 'agent';
    text: string;
    isTransient?: boolean;
}

/**
 * Detects if a message text is generated by a search/read/exploration tool.
 */
export function isExplorationMessage(text: string): boolean {
    const explorationPatterns = [
        /\[DIR\]|\[FILE\]/,
        /list_directory|grep_search|read_file/,
        /Using Ripgrep|Falling back to standard grep/,
        /File modified|File updated|Replacement successfully performed/,
        /📝 \*File modified\*|📝 \*Multi-file edit\*|📝 \*File read\*/,
        /🔍 \*Search\*|📂 \*Directory list\*/
    ];
    return explorationPatterns.some(pattern => pattern.test(text));
}

/**
 * Collapses consecutive exploration messages into a single summarized message.
 */
export function collapseMessages(messages: Message[]): Message[] {
    if (messages.length === 0) return [];

    const collapsed: Message[] = [];
    let explorationGroup: Message[] = [];

    const flushExplorationGroup = () => {
        if (explorationGroup.length === 0) return;

        if (explorationGroup.length === 1) {
            collapsed.push(explorationGroup[0]);
        } else {
            // Count specific actions
            let grepCount = 0;
            let readCount = 0;
            let listCount = 0;
            let otherCount = 0;
            const filesTouched = new Set<string>();

            for (const msg of explorationGroup) {
                const txt = msg.text.toLowerCase();
                if (txt.includes('grep') || txt.includes('search')) {
                    grepCount++;
                } else if (txt.includes('read_file') || txt.includes('file read') || txt.includes('reading')) {
                    readCount++;
                } else if (txt.includes('list_directory') || txt.includes('directory list') || txt.includes('listing')) {
                    listCount++;
                } else {
                    otherCount++;
                }

                // Extract potential filenames or paths
                const fileMatches = msg.text.match(/(?:file|path|modified|read)[*\s]*:\s*`?([^`\s\n]+)`?/i);
                if (fileMatches && fileMatches[1]) {
                    filesTouched.add(fileMatches[1].split('/').pop() || fileMatches[1]);
                }
            }

            const actions: string[] = [];
            if (listCount > 0) actions.push(`${listCount} folder listing(s)`);
            if (grepCount > 0) actions.push(`${grepCount} grep search(es)`);
            if (readCount > 0) actions.push(`${readCount} file read(s)`);
            if (otherCount > 0) actions.push(`${otherCount} other exploration(s)`);

            const filesList = filesTouched.size > 0
                ? ` [Touched: ${Array.from(filesTouched).join(', ')}]`
                : '';

            const summaryText = `🔍 *Exploration Suite* — Completed ${explorationGroup.length} actions: ${actions.join(', ')}${filesList}`;

            collapsed.push({
                id: 'collapsed_' + explorationGroup[0].id,
                sender: 'agent',
                text: summaryText
            });
        }
        explorationGroup = [];
    };

    for (const msg of messages) {
        if (msg.sender === 'agent' && isExplorationMessage(msg.text)) {
            explorationGroup.push(msg);
        } else {
            flushExplorationGroup();
            collapsed.push(msg);
        }
    }
    flushExplorationGroup();

    return collapsed;
}
